#!/bin/bash
# GitHub Repository Bağlantı Sorunu Çözüm Rehberi
# Freqtrade Bot Kurulum Troubleshooting

echo "🔧 GitHub Repository Bağlantı Sorunu Çözüm Rehberi"
echo "=================================================="
echo ""

echo "📋 SORUN TESPİTİ:"
echo "1. Önce GitHub bağlantı testini çalıştırın:"
echo ""
echo "cd /home/dcoakelc"
echo "curl -O https://raw.githubusercontent.com/mhmt23/freqtrade-bot1/master/deploy/test_github_connection.sh"
echo "chmod +x test_github_connection.sh"
echo "./test_github_connection.sh"
echo ""

echo "📋 MUHTEMEL ÇÖZÜMLER:"
echo ""

echo "1️⃣ NETWORK/FIREWALL SORUNU:"
echo "   • cPanel shared hosting'de outgoing connections kısıtlı olabilir"
echo "   • Hosting sağlayıcınızla iletişime geçin"
echo "   • Git ve curl komutlarının çalışıp çalışmadığını test edin"
echo ""

echo "2️⃣ GIT KURULUM SORUNU:"
echo "   • Git kurulu değilse:"
echo "   yum install git        # CentOS/RHEL"
echo "   apt-get install git    # Ubuntu/Debian"
echo ""

echo "3️⃣ SSL/TLS SORUNU:"
echo "   • Eğer SSL hatası alırsanız:"
echo "   git config --global http.sslverify false"
echo ""

echo "4️⃣ MANUEL YÜKLEME (GitHub bağlantısı yoksa):"
echo ""
echo "   # ZIP dosyasını indirin ve yükleyin"
echo "   cd /home/dcoakelc"
echo "   curl -L -O https://github.com/mhmt23/freqtrade-bot1/archive/master.zip"
echo "   unzip master.zip"
echo "   mv freqtrade-bot1-master freqtrade-bot1"
echo "   cd freqtrade-bot1/deploy"
echo "   chmod +x clean_install.sh"
echo "   ./clean_install.sh"
echo ""

echo "5️⃣ CURL İLE DOSYA İNDİRME:"
echo ""
echo "   # Tek tek dosyaları indirin"
echo "   cd /home/dcoakelc"
echo "   mkdir -p freqtrade-bot1/deploy"
echo "   cd freqtrade-bot1/deploy"
echo ""
echo "   # Ana script"
echo "   curl -O https://raw.githubusercontent.com/mhmt23/freqtrade-bot1/master/deploy/clean_install.sh"
echo ""
echo "   # Config dosyası"
echo "   curl -O https://raw.githubusercontent.com/mhmt23/freqtrade-bot1/master/deploy/config.json"
echo ""
echo "   # Strategy dosyası"
echo "   curl -O https://raw.githubusercontent.com/mhmt23/freqtrade-bot1/master/deploy/SimpleScalpingStrategy.py"
echo ""
echo "   # Requirements"
echo "   curl -O https://raw.githubusercontent.com/mhmt23/freqtrade-bot1/master/deploy/requirements_simple.txt"
echo ""
echo "   chmod +x clean_install.sh"
echo "   ./clean_install.sh"
echo ""

echo "6️⃣ HOSTING KISITLAMALARI:"
echo "   • Bazı shared hosting'ler Python paket kurulumunu kısıtlar"
echo "   • pip install izinleri olmayabilir"
echo "   • Bu durumda VPS veya dedicated server gerekebilir"
echo ""

echo "📞 DESTEK:"
echo "   • GitHub: https://github.com/mhmt23/freqtrade-bot1"
echo "   • Issues: Repository'de issue açabilirsiniz"
echo ""

echo "🔍 DEBUG KOMUTLARI:"
echo "   • Internet: ping google.com"
echo "   • GitHub: ping github.com"
echo "   • Git: git --version"
echo "   • Python: python3 --version"
echo "   • Pip: pip3 --version"
